# Generated by Django 5.2.1 on 2025-06-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_alter_quarto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.quarto'),
        ),
    ]
