# Generated by Django 5.2.1 on 2025-06-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_alter_reserva_data_reserva_alter_reserva_quarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='status',
            field=models.BooleanField(choices=[(1, 'Disponível'), (0, 'Reservado')], default=1),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Premium', 'Premium'), ('Plus', 'Plus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(),
        ),
    ]
