# Generated by Django 5.2.3 on 2025-06-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_alter_quarto_status_alter_quarto_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_checkin',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_checkout',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
